version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: 'finlandb'
      MYSQL_USER: 'finnlanadmin'
      MYSQL_PASSWORD: 'Official@tech'
      MYSQL_ROOT_PASSWORD: 'root@toor#321'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/ubuntu/data/:/var/lib/mysql

  backend:
    image: frinlan
    build: .
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql_db:3306/finlandb?useSSL=false'
      SPRING_DATASOURCE_USERNAME: 'finnlanadmin'
      SPRING_DATASOURCE_PASSWORD: 'Official@tech'
    expose:
      - '8080'
    depends_on:
      - "db"

  frontend:
    image: frinlan-frontend
    build: ../frinlen-front
    ports:
      - '3000:80'
    expose:
      - '80'

